# This workflow builds PyInstaller single-file executables of Meerk40t
# for Windows and Linux (and hopefully future Mac)
# Future: May also build an NSIS installer

name: Build executables

on:
#  release:
#    types: [published]
  push:
    branches: [main, legacy, 0.7]
  pull_request:
    branches: [main, legacy, 0.7]

concurrency:
  group: builds-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-centos7:
    runs-on: centos7
    steps:
    - name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2

    - name: Ensure latest meerk40t-camera
      run: |
        pip3 install --upgrade --upgrade-strategy eager meerk40t-camera opencv-python-headless

    - name: List Python environment
      run: |
        pip3 list

    - name: Build Meerk40t
      run: |
        mv meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t .github/workflows/linux/meerk40t.spec
        mv mk40t.py meerk40t.py
        mv dist/MeerK40t dist/MeerK40t-linux
        if [ "${GITHUB_EVENT_NAME}" != "release" ]; then
            mv dist/MeerK40t-linux dist/MeerK40t-linux-${GITHUB_SHA}
        fi
        ls -l dist

    - name: Upload built executable
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/MeerK40t-linux

    - name: Upload artifacts
      if: ${{ github.event_name != 'release' }}
      uses: actions/upload-artifact@v2
      with:
        name: Builds
        if-no-files-found: error
        path: |
          dist/MeerK40t-linux-${GITHUB_SHA}


  build-ubuntu:
    # Do not run as we are now using centos for Linux builds
    #if: ${{ false }}
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout meerk40t
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Python Cache - ubuntu-18.04-python39
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ubuntu-18.04-python39

    - name: Install dependencies
      run: |
        sudo apt-get install libgtk-3-dev
        python3 -m pip install --upgrade --upgrade-strategy eager pip
        pip3 install --upgrade --upgrade-strategy eager pyinstaller wheel
        pip3 install --upgrade --upgrade-strategy eager -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
        if [ -f requireoptions.txt ]; then pip3 install --upgrade --upgrade-strategy eager -r requireoptions.txt; fi

    - name: List Python environment
      run: |
        pip3 list

    - name: Build meerk40t
      run: |
        mv meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t mk40t.py
        mv mk40t.py meerk40t.py
        mv dist/meerk40t dist/MeerK40t-ubuntu-18.04
        if [ "${GITHUB_EVENT_NAME}" != "release" ]; then
            mv dist/MeerK40t-ubuntu-18.04 dist/MeerK40t-ubuntu-${{ github.sha }}
        fi
        ls -l dist

    - name: Upload built executable
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/MeerK40t-Ubuntu-18.04

    - name: Upload artifacts
      if: ${{ github.event_name != 'release' }}
      uses: actions/upload-artifact@v2
      with:
        name: Builds
        if-no-files-found: error
        path: |
          dist/MeerK40t-ubuntu-${{ github.sha }}


  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout meerk40t
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: 'x86'
# Yikes. ch341dll.dll is not compatible with 64-bit python/pyinstaller/ctypes
#
# Python 3.7, wxPython 4.0.7-post2 is specifically chosen to workaround
# issue meerk40t/meerk40t#242, once the SetLocale issue is resolved, we can test
# newer versions again. Python 3.8 is latest possible for Windows 7 support.

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade --upgrade-strategy eager pip
        pip3 install --upgrade --upgrade-strategy eager wheel
        pip install --upgrade --upgrade-strategy eager meerk40t-camera ezdxf opencv-python-headless

# Compile bootloaders in order to reduce virus totals
# PYTHONHASHSEED is an attempt to get deterministic builds for VirusTotal
    - name: Build pyinstaller, generate bootloaders
      env:
        PYTHONHASHSEED: 12506
      run: |
        git clone --depth=1 https://github.com/pyinstaller/pyinstaller
        cd pyinstaller/bootloader
        python3 ./waf distclean all --target-arch=32bit
        cd ..
        python3 setup.py install
        cd ..

    - name: List Python environment
      run: |
        pip3 list

    - name: Build MeerK40t (wxPython 4.0.7-post2)
      run: |
        pip install wxPython==4.0.7-post2
        mv meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t .github/workflows/win/meerk40t.spec
        mv mk40t.py meerk40t.py
        mv dist/meerk40t.exe dist/wx-MeerK40t.exe
        if [ "${GITHUB_EVENT_NAME}" != "release" ]; then
            mv dist/wx-MeerK40t.exe dist/wx-MeerK40t-${{ github.sha }}.exe
        fi
        ls -l dist

    - name: Build MeerK40t (wxPython 4.1.1)
      run: |
        pip install wxPython==4.1.1
        mv meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t .github/workflows/win/meerk40t.spec
        mv mk40t.py meerk40t.py
        mv dist/meerk40t.exe dist/MeerK40t.exe
        if [ "${GITHUB_EVENT_NAME}" != "release" ]; then
            mv dist/MeerK40t.exe dist/MeerK40t-${{ github.sha }}.exe
        fi
        ls -l dist

    - name: Upload built executable
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/MeerK40t.exe
          dist/wx-MeerK40t.exe

    - name: Upload artifacts
      if: ${{ github.event_name != 'release' }}
      uses: actions/upload-artifact@v2
      with:
        name: Builds
        if-no-files-found: error
        path: |
          dist/MeerK40t-${{ github.sha }}.exe
          dist/wx-MeerK40t-${{ github.sha }}.exe
