name: BuildBoxTest

on:
  workflow_dispatch:

jobs:
  check-mac:
    runs-on: mac-latest
    steps:
    - name: system_profiler basic
      run: |
        system_profiler -detailLevel basic
    - name: system_profiler full
      run: |
        system_profiler
